Repository jupyterhub/nativeauthenticator, pull requests merged in 2021-11, with the labels that each got.

#183 document and refactor the handlers
  nativeauthenticator/handlers.py
  nativeauthenticator/nativeauthenticator.py
  nativeauthenticator/tests/test_authenticator.py
Labels: documentation, maintenance

#188 docs: c.NativeAuthenticator instead of c.Authenticator
  README.md
  docs/source/options.md
  docs/source/quickstart.md
  docs/source/troubleshooting.md
Labels: documentation

#195 Correct login procedure for admins
  nativeauthenticator/handlers.py
  nativeauthenticator/nativeauthenticator.py
Labels: bug
